### ISSUE TITLE
What happened to docs page?

### ISSUE THREAD

**Issue by monodyle** [moaijs/moai#183]
Some pages missing props explain, some pages missing props description.

![image](https://user-images.githubusercontent.com/30283022/118481267-7c3a0f80-b73d-11eb-9ac0-6aa185358bb9.png)

![image](https://user-images.githubusercontent.com/30283022/118481306-8956fe80-b73d-11eb-9a48-234673d011d9.png)

What is going on @thien-do?

**Comment by thien-do** [comment]
Sorry :( I really don't know. This is super bad :(

Some initial thoughts:
- Don't know yet why some arg tables are shown, and some aren't
- For those that are shown, the description is lost, which may related to the DocGen (ReactDocGen to be exact I think)
- In local dev, they are all fine
- In a local build, I can't even get pass the loading stage (yarn run build then npx server it)

**Comment by thien-do** [comment]
It's most likely, IMO, that Vercel's monorepo deployment prevents a folder from accessing the files outside of it (doc is sibling of "core", so it can't access the source file via "..")

That is weird, though, because the "stories" does indeed use ".." to import "core" and "gallery" a lot, and look like they're fine
