### ISSUE TITLE
Table expand icon cell takes up too much space 

### ISSUE THREAD

**Issue by clitetailor** [moaijs/moai#229]
Currently, every columns are taking a proportion of space even with the table's expand icon. The icon cell width should be fixed and does not take up other cell space.

![image (2)](https://user-images.githubusercontent.com/16368559/122444367-a7c54980-cfca-11eb-881b-5fbedceaeae4.png)

**Comment by lqt93** [comment]
@thien-do Could you brief solution for this issue?

**Comment by thien-do** [comment]
Ah actually I think this is an easy issue:

1. Understand what makes that space (divpx or margin)
2. Avoid render that space if only 1 item is rendered

This is because the first column of the table is used for 2 things: the expand button and the checkbox/radio for selectable rows. The space above is the space between these 2. It should not happen if there's only one.

I think the ideal solution is to use gap, but may it's not widely supported yet, so we can use the owl selector (* + *)

**Comment by clitetailor** [comment]
> This is because the first column of the table is used for 2 things: the expand button and the checkbox/radio for selectable rows. The space above is the space between these 2. It should not happen if there's only one.

@thien-do @lqt93 

Nope, the gap does nothing in this case. The problem is the content of the expanded row is so large that it stretches all the table width including the first column.

![image](https://user-images.githubusercontent.com/16368559/125501023-235b7153-b9c7-4f70-8cc1-5d774b61d6e4.png)

IMO, the easiest solution is to set the action column width column to 0px or 1px to make the first column fit to the content size and does not stretch again.

![image](https://user-images.githubusercontent.com/16368559/125501954-caa4a97b-0559-4e0f-b217-820c5c91291a.png)
