### ISSUE TITLE
Flash of white style when you first load the page

### ISSUE THREAD

**Issue by rauchg** [moaijs/moai#63]
Great job on Moai – I love it.
If I have the dark theme activated, I see a flash of the light theme when I first load https://moaijs.com/

**Comment by thien-do** [comment]
Thank you @rauchg ! Yeah that's a bad bug...

In case you're curious, it's because the light theme is set on the first render ([_document](https://github.com/moaijs/moai/blob/204c3f788615f25f878a74cc4cf495d33f60a8eb/site/pages/_document.tsx#L6-L9)) and then the built-in theme switcher [reset](https://github.com/moaijs/moai/blob/204c3f788615f25f878a74cc4cf495d33f60a8eb/core/src/theme/theme.tsx#L34-L39) it in an effect hook.

The correct way should be to set the correct theme right in the _document in the first place
